from exceptions.BaseException import BaseException

class WrongUserException(BaseException):
    pass